name: sentinel-initial

services:
  postgres:
    image: postgres:latest
    container_name: sentinel_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - sentinel_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: sentinel_redis
    ports:
      - "6379:6379"
    volumes:
      - sentinel_redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

volumes:
  sentinel_postgres_data:
  sentinel_redis_data:
