package dev.sentinel.domain.shared.enums;

public enum PermissionCode {
  APPLICATION_READ,
  APPLICATION_CREATE,
  APPLICATION_UPDATE,
  APPLICATION_DELETE,
  ENVIRONMENT_READ,
  ENVIRONMENT_CREATE,
  ENVIRONMENT_UPDATE,
  ENVIRONMENT_DELETE,
  FLAG_READ,
  FLAG_CREATE,
  FLAG_UPDATE,
  FLAG_DELETE,
  FLAG_ENABLE,
  FLAG_DISABLE,
  RULE_READ,
  RULE_CREATE,
  RULE_UPDATE,
  RULE_DELETE,
  AUDIT_READ,
  MEMBER_INVITE,
  MEMBER_REMOVE,
  MEMBER_ROLE_ASSIGN,
  TOKEN_CREATE,
  TOKEN_REVOKE;
}
